Repository nervosnetwork/huobi-chain, pull requests merged in 2020-07, with the labels that each got.

#1 chore: Add jenkins-x ci
  OWNERS
  OWNERS_ALIASES
  jenkins-x-clippy.yml
  jenkins-x-fmt.yml
  jenkins-x-unit.yml
  jenkins-x.yml
  jenkinx-x-e2e.yml
  skaffold.yaml
Labels: size/L

#2 fix(test): e2e tests
  Cargo.lock
  Cargo.toml
  config/genesis.toml
  src/main.rs
  tests/e2e/asset.test.ts
  tests/e2e/basic.test.ts
  tests/e2e/helper.ts
  tests/e2e/node_manager.test.ts
  tests/e2e/package.json
  tests/e2e/riscv.test.ts
  tests/e2e/tsconfig.json
  tests/e2e/utils.ts
  tests/e2e/yarn.lock
Labels: approved, lgtm, size/XXL

#4 feat(main): register kyc and multi-signature service in main function
  Cargo.lock
  Cargo.toml
  src/main.rs
Labels: approved, lgtm, size/XS

#5 fix: package.json, lint
  package-lock.json
  tests/e2e/.eslintrc.js
  tests/e2e/asset.test.ts
  tests/e2e/basic.test.ts
  tests/e2e/change_validators/change_validators_test.ts
  tests/e2e/change_validators/common.ts
  tests/e2e/change_validators/create_configs.ts
  tests/e2e/helper.ts
  tests/e2e/package.json
  tests/e2e/riscv.test.ts
  tests/e2e/tsconfig.json
  tests/e2e/utils.ts
  tests/e2e/yarn.lock
Labels: approved, lgtm, size/L

#8 feat!: bump version of muta and toolchain to fit event
  Cargo.lock
  Cargo.toml
  rust-toolchain
  services/admission_control/Cargo.toml
  services/admission_control/src/lib.rs
  services/admission_control/src/tests.rs
  services/admission_control/src/types.rs
  services/asset/Cargo.toml
  services/asset/src/lib.rs
  services/asset/src/tests/mod.rs
  services/asset/src/types.rs
  services/governance/Cargo.toml
  services/governance/src/lib.rs
  services/governance/src/tests/mod.rs
  services/governance/src/tests/test_genesis.toml
  services/governance/src/types.rs
  services/kyc/Cargo.toml
  services/kyc/src/error.rs
  services/kyc/src/lib.rs
  services/kyc/src/tests.rs
  services/kyc/src/types.rs
  services/metadata/Cargo.toml
  services/riscv/Cargo.toml
  services/riscv/src/error.rs
  services/riscv/src/lib.rs
  services/riscv/src/tests/mod.rs
  services/riscv/src/types.rs
  services/riscv/src/vm/c/libpvm.a
  services/riscv/src/vm/c/pvm.c
  services/riscv/src/vm/c/pvm.h
  services/riscv/src/vm/syscall/chain_interface.rs
  services/riscv/src/vm/syscall/environment.rs
Labels: approved, lgtm, size/XL

#10 feat!: fix asset service and modify payload
  services/asset/src/lib.rs
  services/asset/src/tests/mod.rs
  services/asset/src/types.rs
Labels: approved, lgtm, size/L

#9 feat!: remove duktape as it has no long been supported
  Makefile
  node_modules/.yarn-integrity
  services/riscv/src/tests/duktape.rs
  services/riscv/src/tests/general
  services/riscv/src/tests/general.c
  services/riscv/src/tests/test_code.js
  services/riscv/src/types.rs
  services/riscv/src/vm/c/duktape_ee.bin
  services/riscv/src/vm/c/duktape_ee.c
  services/riscv/src/vm/c/duktape_ee_helper.h
  services/riscv/src/vm/interpreter.rs
  services/riscv/src/vm/syscall/debug.rs
Labels: approved, lgtm, size/XXL

#13 fix(kyc)!: change change_service_admin's payload type
  services/kyc/src/lib.rs
  services/kyc/src/tests.rs
  services/kyc/src/types.rs
Labels: approved, size/M

#6 refactor(service): avoid using expect in tx hook
  config/genesis.toml
  services/admission_control/src/lib.rs
  services/asset/src/lib.rs
  services/governance/src/lib.rs
  services/governance/src/tests/mod.rs
  services/kyc/src/lib.rs
Labels: approved, lgtm, size/L

#14 feat(asset): multi issuers support in genesis
  config/genesis.toml
  services/asset/src/lib.rs
  services/asset/src/tests/mod.rs
  services/asset/src/types.rs
  services/governance/src/tests/test_genesis.toml
  tests/e2e/genesis.toml
Labels: size/L

#16 Revert "feat(asset): multi issuers support in genesis"
  config/genesis.toml
  services/asset/src/lib.rs
  services/asset/src/tests/mod.rs
  services/asset/src/types.rs
  services/governance/src/tests/test_genesis.toml
  tests/e2e/genesis.toml
Labels: size/L

#12 test(integration): add integration test framework
  .travis.yml
  Cargo.lock
  Cargo.toml
  config/genesis.toml
  services/admission_control/Cargo.toml
  services/asset/Cargo.toml
  services/asset/src/lib.rs
  services/asset/src/types.rs
  services/governance/Cargo.toml
  services/governance/src/lib.rs
  services/governance/src/tests/mod.rs
  services/governance/src/types.rs
  services/kyc/Cargo.toml
  services/metadata/Cargo.toml
  services/riscv/Cargo.toml
  tests/integration/mod.rs
  tests/integration/service_test.rs
  tests/integration/test_genesis.toml
  tests/integration/types.rs
  tests/test.rs
Labels: approved, lgtm, size/XL

#17 feat(asset): multi issuer support in genesis (#14)
  config/genesis.toml
  services/asset/src/lib.rs
  services/asset/src/tests/mod.rs
  services/asset/src/types.rs
  services/governance/src/tests/mod.rs
  services/governance/src/tests/test_genesis.toml
  services/governance/src/types.rs
  tests/e2e/genesis.toml
  tests/integration/test_genesis.toml
Labels: approved, lgtm, size/L

#18 fix(gov): clear fee at tx_hook_before
  services/governance/src/lib.rs
Labels: approved, lgtm, size/XS

#23 doc(riscv): update document
  docs/riscv_service.md
Labels: approved, lgtm, size/M

#24 change(governance): directly transfer fee to block miner
  services/governance/src/lib.rs
  services/governance/src/tests/mod.rs
  services/governance/src/types.rs
  tests/integration/mod.rs
  tests/integration/service_test.rs
Labels: approved, lgtm, size/L

#22 feat: asset, kyc, riscv, basic e2e tests
  services/asset/src/lib.rs
  services/asset/src/tests/mod.rs
  services/riscv/src/tests/mod.rs
  tests/e2e/asset.test.ts
  tests/e2e/basic.test.ts
  tests/e2e/kyc.test.ts
  tests/e2e/package.json
  tests/e2e/riscv.test.ts
  tests/e2e/riscv_contracts/contract_test
  tests/e2e/riscv_contracts/contract_test.c
  tests/e2e/utils.ts
  tests/e2e/yarn.lock
Labels: approved, lgtm, size/XL

#27 feat: modify docs of asset_service and metadata_service
  docs/asset_service.md
  docs/metadata_service.md
Labels: approved, lgtm, size/L

#26 refactor(asset): give each asset an administrator
  config/genesis.toml
  services/asset/src/lib.rs
  services/asset/src/tests/mod.rs
  services/asset/src/types.rs
  services/governance/src/tests/test_genesis.toml
  tests/e2e/genesis.toml
  tests/integration/service_test.rs
  tests/integration/test_genesis.toml
Labels: size/L

#25 feat(service): add query admin method for service
  services/admission_control/src/lib.rs
  services/governance/src/lib.rs
  services/governance/src/tests/mod.rs
  services/kyc/src/error.rs
  services/kyc/src/lib.rs
  services/kyc/src/tests.rs
  services/riscv/src/authorization.rs
  services/riscv/src/error.rs
  services/riscv/src/lib.rs
  services/riscv/src/tests/mod.rs
  services/riscv/src/types.rs
Labels: approved, lgtm, size/L

#29 feat: test tx_hook
  tests/e2e/governance.test.ts
  tests/e2e/riscv_contracts/contract_test
  tests/e2e/riscv_contracts/contract_test.c
  tests/e2e/tsconfig.json
  tests/e2e/utils.ts
Labels: approved, lgtm, size/L

#28 fix(governance): emit only one charge fee event
  services/asset/src/lib.rs
  services/asset/src/tests/mod.rs
  services/governance/src/lib.rs
  services/governance/src/tests/mod.rs
  services/governance/src/types.rs
Labels: approved, lgtm, size/L

#31 refactor(asset): rename transfer and transfer from
  services/asset/src/lib.rs
  services/asset/src/tests/mod.rs
  services/governance/src/lib.rs
Labels: approved, lgtm, size/M

#32 build: use latest muta for test, which contains inner_call, bech32
  Cargo.lock
  Cargo.toml
  config/chain.toml
  config/genesis.toml
  services/admission_control/Cargo.toml
  services/asset/Cargo.toml
  services/asset/src/lib.rs
  services/authorization/Cargo.toml
  services/governance/Cargo.toml
  services/kyc/Cargo.toml
  services/metadata/Cargo.toml
  services/metadata/src/tests/mod.rs
  services/riscv/Cargo.toml
  services/riscv/src/lib.rs
  services/riscv/src/vm/syscall/environment.rs
  tests/e2e/genesis.toml
  tests/integration/test_genesis.toml
Labels: approved, lgtm, size/L

#33 fix: update genesis by using known private
  config/genesis.toml
Labels: approved, lgtm, size/S
